# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mleech/gr-ra_blocks/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mleech/gr-ra_blocks/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mleech/gr-ra_blocks/trunk/CMakeFiles /home/mleech/gr-ra_blocks/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mleech/gr-ra_blocks/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named gnuradio-ra_blocks

# Build rule for target.
gnuradio-ra_blocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gnuradio-ra_blocks
.PHONY : gnuradio-ra_blocks

# fast build rule for target.
gnuradio-ra_blocks/fast:
	$(MAKE) -f lib/CMakeFiles/gnuradio-ra_blocks.dir/build.make lib/CMakeFiles/gnuradio-ra_blocks.dir/build
.PHONY : gnuradio-ra_blocks/fast

#=============================================================================
# Target rules for targets named test-ra_blocks

# Build rule for target.
test-ra_blocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-ra_blocks
.PHONY : test-ra_blocks

# fast build rule for target.
test-ra_blocks/fast:
	$(MAKE) -f lib/CMakeFiles/test-ra_blocks.dir/build.make lib/CMakeFiles/test-ra_blocks.dir/build
.PHONY : test-ra_blocks/fast

#=============================================================================
# Target rules for targets named _ra_blocks_swig

# Build rule for target.
_ra_blocks_swig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _ra_blocks_swig
.PHONY : _ra_blocks_swig

# fast build rule for target.
_ra_blocks_swig/fast:
	$(MAKE) -f swig/CMakeFiles/_ra_blocks_swig.dir/build.make swig/CMakeFiles/_ra_blocks_swig.dir/build
.PHONY : _ra_blocks_swig/fast

#=============================================================================
# Target rules for targets named _ra_blocks_swig_doc_tag

# Build rule for target.
_ra_blocks_swig_doc_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _ra_blocks_swig_doc_tag
.PHONY : _ra_blocks_swig_doc_tag

# fast build rule for target.
_ra_blocks_swig_doc_tag/fast:
	$(MAKE) -f swig/CMakeFiles/_ra_blocks_swig_doc_tag.dir/build.make swig/CMakeFiles/_ra_blocks_swig_doc_tag.dir/build
.PHONY : _ra_blocks_swig_doc_tag/fast

#=============================================================================
# Target rules for targets named _ra_blocks_swig_swig_tag

# Build rule for target.
_ra_blocks_swig_swig_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _ra_blocks_swig_swig_tag
.PHONY : _ra_blocks_swig_swig_tag

# fast build rule for target.
_ra_blocks_swig_swig_tag/fast:
	$(MAKE) -f swig/CMakeFiles/_ra_blocks_swig_swig_tag.dir/build.make swig/CMakeFiles/_ra_blocks_swig_swig_tag.dir/build
.PHONY : _ra_blocks_swig_swig_tag/fast

#=============================================================================
# Target rules for targets named pygen_swig_e554d

# Build rule for target.
pygen_swig_e554d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pygen_swig_e554d
.PHONY : pygen_swig_e554d

# fast build rule for target.
pygen_swig_e554d/fast:
	$(MAKE) -f swig/CMakeFiles/pygen_swig_e554d.dir/build.make swig/CMakeFiles/pygen_swig_e554d.dir/build
.PHONY : pygen_swig_e554d/fast

#=============================================================================
# Target rules for targets named pygen_python_e2a73

# Build rule for target.
pygen_python_e2a73: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pygen_python_e2a73
.PHONY : pygen_python_e2a73

# fast build rule for target.
pygen_python_e2a73/fast:
	$(MAKE) -f python/CMakeFiles/pygen_python_e2a73.dir/build.make python/CMakeFiles/pygen_python_e2a73.dir/build
.PHONY : pygen_python_e2a73/fast

#=============================================================================
# Target rules for targets named pygen_python_f681d

# Build rule for target.
pygen_python_f681d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pygen_python_f681d
.PHONY : pygen_python_f681d

# fast build rule for target.
pygen_python_f681d/fast:
	$(MAKE) -f python/CMakeFiles/pygen_python_f681d.dir/build.make python/CMakeFiles/pygen_python_f681d.dir/build
.PHONY : pygen_python_f681d/fast

#=============================================================================
# Target rules for targets named pygen_apps_9a6dd

# Build rule for target.
pygen_apps_9a6dd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pygen_apps_9a6dd
.PHONY : pygen_apps_9a6dd

# fast build rule for target.
pygen_apps_9a6dd/fast:
	$(MAKE) -f apps/CMakeFiles/pygen_apps_9a6dd.dir/build.make apps/CMakeFiles/pygen_apps_9a6dd.dir/build
.PHONY : pygen_apps_9a6dd/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... gnuradio-ra_blocks"
	@echo "... test-ra_blocks"
	@echo "... _ra_blocks_swig"
	@echo "... _ra_blocks_swig_doc_tag"
	@echo "... _ra_blocks_swig_swig_tag"
	@echo "... pygen_swig_e554d"
	@echo "... pygen_python_e2a73"
	@echo "... pygen_python_f681d"
	@echo "... pygen_apps_9a6dd"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

